### PR TITLE
Downloading script

### PR DESCRIPTION
**Pull request by universome**
Hi! I am not sure if it is allowed (from the licensing perspective) to have a download script in your repo, but just in case it might be useful to anyone, here the script which I used to download/cut/resize the videos. It downloads almost all the videos (except those videos that have been removed or went private).

### CODE REVIEW

**Comment by MRzzm** [comment]
Hi, Thank you for sharing the script of data processing. I'm so sorry that it is not allowed to provide any code of video editing by the license, so I add your links in the _readme_.

**Comment by universome** [comment]
Hi! This is fine, I suspected that you didn't release your own download script for legal reasons and that's why didn't expect that you could release mine. I created this pull request just in case

**Comment by 649459021** [comment]
> Hi! This is fine, I suspected that you didn't release your own download script for legal reasons and that's why didn't expect that you could release mine. I created this pull request just in case

Hi,  thanks for you script. I noticed that your script download video without audio.  I don't why you do this. If I want to download video with audio, I should modify the youtube-dl commond line 'bestvideo' -> 'best'.  Is that right?

**Comment by universome** [comment]
Hi, @649459021! I download videos without audio for two reasons: 1) I do not need audio anyway; and 2) `bestvideo` sometimes downloads videos in a better resolution than `best`. If you want audio you can either download with the `best` option, as you specified or you can download them separately and then merge

**Comment by 649459021** [comment]
> Hi, @649459021! I download videos without audio for two reasons: 1) I do not need audio anyway; and 2) `bestvideo` sometimes downloads videos in a better resolution than `best`. If you want audio you can either download with the `best` option, as you specified or you can download them separately and then merge

Thanks for your reply!

**Pull request closed without merging**
